name: Build macOS App

on:
  push:
    branches:
      - main  # Сборка будет запускаться при пуше в ветку main

jobs:
  build:
    runs-on: macos-latest  # Указывает, что сборка должна происходить на macOS

    steps:
      - name: Checkout code  # Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Set up Python  # Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies  # Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip
          pip install py2app pillow

      - name: Create dist directory if not exists  # Создаем директорию dist
        run: |
          mkdir -p dist

      - name: Debug environment  # Отладочная информация
        run: |
          python --version
          pip list
          ls -la

      - name: Build macOS app  # Собираем приложение
        run: |
          python setup.py py2app

      - name: Upload artifact  # Загружаем готовое приложение
        uses: actions/upload-artifact@v3
        with:
          name: ISP_Program_3  # Имя артефакта
          path: dist/Visual_7.0_Full_CSV_to_AE.app  # Путь к собранному приложению
